version: 2
jobs:
  build:
    docker:
      - image: jorgenpo/projectx-server
    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    steps:
      - checkout

      - run: make generate
      - run: mkdir bin
      - run: CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o bin/projectx-server-linux64
      - run: CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build -o bin/projectx-server-windows64.exe
      - run: ./bin/projectx-server-linux64 --version > version.txt
      - run: mv bin/projectx-server-linux64 bin/projectx-server-$(cat version.txt)-${CIRCLE_BRANCH}-linux64
      - run: mv bin/projectx-server-windows64.exe bin/projectx-server-$(cat version.txt)-${CIRCLE_BRANCH}-windows64.exe
      - store_artifacts:
          path: bin
workflows:
  version: 2
  build:
    jobs:
      - build
